### ISSUE TITLE
Ntfy and Nextpush

### ISSUE THREAD

**Issue by bastiencyr** [UP-NextPush/android#47]
Hey, 
What are the differences between Nextpush and ntfy. I'm a little bit surprised that I have to install Nextpush to make my notifications working. Why Talk doesnt work with ntfy ? 
Bastien

**Comment by p1gp1g** [comment]
NextPush and ntfy are both UnifiedPush distributors : they can be used by applications *supporting UnifiedPush* to get notifications.

NextPush is pretty easy to self-host if you already have a self-hosted Nextcloud server since the server side is a Nextcloud application. NextPush does not support (yet ?) custom notifications (send with a command line), which can be useful in scripts.
Ntfy on its side has a built-in default server and is also easy to self-host (you need to run the binary). It also support custom notifications, which is actually its main purpose.

Finally, Talk does not support UnifiedPush : you won't get notification with NextPush or Ntfy

**Comment by bastiencyr** [comment]
Hello @p1gp1g, Thanks for your answers, Its clearer now !

**Comment by p1gp1g** [comment]
I'm closing this issue since it has been answered :)
